Repository Priyaaa1/StartConnect-Hub, pull requests merged in 2024-05, with the labels that each got.

#22 Fixed navbar, footer, login and signup
  src/Components/Contact/Contact.jsx
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
  src/Components/Login/Login.css
  src/Components/Login/Login.jsx
  src/Components/Navbar/Navbar.jsx
  src/Components/Signup/Signup.css
  src/Components/Signup/Signup.jsx
  src/index.css
Labels: good first issue, GSSoC'24

#25 Add Hover effect
  src/Components/Navbar/Navbar.css
  src/index.css
Labels: enhancement, good first issue, GSSoC'24, level 1

#47 added testimonials
  package-lock.json
  package.json
  public/user-1.png
  public/user-2.png
  public/user-3.png
  public/user-4.png
  public/user-5.jpg
  public/user-6.jpg
  src/App.jsx
  src/Components/Navbar/Navbar.jsx
  src/Components/Testimonials/Testimonial.css
  src/Components/Testimonials/Testimonials.jsx
Labels: enhancement, GSSoC'24, level 3

#48 Added Favicon
  index.html
  src/assets/fav2.ico
Labels: enhancement, GSSoC'24, level 1

#75 Fix Mobile Responsiveness Issue on Homepage
  package.json
  src/Components/Testimonials/Testimonial.css
  src/Components/Testimonials/Testimonials.jsx
Labels: GSSoC'24, level 2

#105 Enhancement of Footer Effects for Improved User Experience
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
Labels: enhancement, good first issue, GSSoC'24, level 2

#100 styling of login and signup button
  src/Components/Login/Login.css
  src/Components/Signup/Signup.css
Labels: GSSoC'24, level 1

#124 Added a Vertical Scrollbar and Scroll to Top button
  package-lock.json
  package.json
  src/App.jsx
  src/Components/GoToTop.jsx
  src/index.css
Labels: enhancement, gssoc, level2

#120 Fixes #103 and #110
  src/Components/Hero/Hero.css
  src/Components/Navbar/Navbar.jsx
Labels: enhancement, gssoc, level2

#127 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, gssoc, level2

#133 Adding FAQ feature
  src/App.css
  src/App.jsx
  src/Components/About/About.css
  src/Components/About/About.jsx
  src/Components/Contact/Contact.css
  src/Components/FAQ/accordian.css
  src/Components/FAQ/accordian.jsx
  src/Components/FAQ/data.js
  src/Components/Navbar/Navbar.jsx
  src/Components/Testimonials/Testimonial.css
  src/Components/Title/Title.css
Labels: enhancement, gssoc, level3

#162 Changed the Navbar.css and added few css to make Navbar responsive
  src/Components/Navbar/Navbar.css
Labels: gssoc, level1

#160 Fixed the postion of carousel nav button
  src/Components/Testimonials/Testimonial.css
  src/Components/Testimonials/Testimonials.jsx
Labels: gssoc, level1

#171 Made few changes in the ChatBot
  package-lock.json
  package.json
  public/chatbotLogo.jpeg
  public/userAvatar.jpg
  src/App.jsx
  src/Components/ChatAssistant/Avatar.jsx
  src/Components/ChatAssistant/ChatAssistant.css
  src/Components/ChatAssistant/ChatAssistant.jsx
  src/Components/ChatAssistant/UserAvatar.jsx
  src/Components/ChatBot/ActionProvider.jsx
  src/Components/ChatBot/MessageParser.jsx
  src/Components/ChatBot/config.jsx
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/Navbar.jsx
Labels: gssoc, level3

#172 Update README with improved contribution guidelines
  README.md
Labels: documentation

#195 Enhanced chatbot scrollbar
  src/Components/ChatAssistant/ChatAssistant.css
  src/Components/ChatAssistant/ChatAssistant.jsx
Labels: enhancement, gssoc, level1

#198 Updated GoToTop.jsx and Reposition the button
  src/Components/GoToTop.jsx
Labels: bug, gssoc, level1

#190 Added link to "FAQ" in footer
  src/Components/Footer/Footer.jsx
Labels: gssoc, level1

#170 Abhisharma1511
  src/App.css
  src/App.jsx
  src/Components/About/About.css
  src/Components/About/About.jsx
  src/Components/Contact/Contact.css
  src/Components/Contact/Contact.jsx
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
  src/Components/Hero/Hero.css
  src/Components/Hero/Hero.jsx
Labels: gssoc, level1

#219 Explore Page Fixes Issue #207
  index.html
  package-lock.json
  package.json
  public/explore-img1.png
  public/investor-management.png
  src/App.jsx
  src/Components/Hero/Hero.jsx
  src/Pages/Explore.css
  src/Pages/Explore.jsx
  src/main.jsx
Labels: gssoc, level2

#212 Fixed issue of chatbot css in Input Field and added hover effect.
  src/Components/ChatAssistant/ChatAssistant.css
  src/Components/Testimonials/Testimonial.css
Labels: enhancement, gssoc, level1

#220 Fixed #138 (taking only number input in phone number while sending message)
  src/Components/Contact/Contact.jsx
Labels: gssoc, level1

#201 Fix issue #173
  src/Components/About/About.css
  src/Components/Footer/Footer.css
  src/Components/Navbar/Navbar.jsx
  src/index.css
Labels: gssoc, level1

#197 fixes outline error #196
  src/Components/Login/Login.css
  src/Components/Signup/Signup.css
Labels: gssoc, level1

#229 Added "How it Works, Vision & Mission, Privacy Policy and Terms & Conditions" Pages to the Website
  src/App.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Navbar/Navbar.css
  src/Pages/HowItWorks.jsx
  src/Pages/PrivacyPolicy.jsx
  src/Pages/TermsAndConditions.jsx
  src/Pages/VisionAndMission.jsx
Labels: gssoc, level2

#226 Fixed The issue of Testimonial cards Overlaping The ChatBot.
  src/Components/ChatAssistant/ChatAssistant.css
  src/Components/FAQ/accordian.css
Labels: bug, gssoc, level1

#227 Enhanced FAQ section with icons and smooth scrolling
  src/Components/FAQ/accordian.css
  src/Components/FAQ/accordian.jsx
Labels: gssoc, level1

#167 GOOGLE LOGIN AND SIGNUP FEATURE ADDED
  package-lock.json
  package.json
  src/Components/Login/Login.jsx
  src/Components/Signup/Signup.jsx
  src/main.jsx
Labels: gssoc, level1

#236 Adding a README file, Installation and Setup Guide
  README.md
Labels: documentation, gssoc, level1

#243 Added meta elements that enhance SEO performance
  index.html
Labels: gssoc, level1

#237 modified: Change the twitter logo to latest one
  src/Components/Footer/Footer.jsx
Labels: enhancement, gssoc

#221 Added UI of the About Us, Contact Us and Faq section of the footer section of the website
  package-lock.json
  package.json
  src/App.jsx
  src/Components/About/About.jsx
  src/Components/FAQ/accordian.jsx
  src/Components/Footer/Components/AboutUS.jsx
  src/Components/Footer/Components/Contact.css
  src/Components/Footer/Components/Main.css
  src/Components/Footer/Components/contact.jsx
  src/Components/Footer/Components/data.js
  src/Components/Footer/Components/faq.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Hero/Hero.jsx
  src/Components/Testimonials/Testimonials.jsx
Labels: gssoc, level2

#262 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, gssoc, level1

#245 Updated the UI of the Footer
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
  src/Components/Navbar/Navbar.jsx
Labels: gssoc, level2

#271 Edited Dynamic code for year
  src/Components/Footer/Footer.jsx
Labels: gssoc

#276 Fix: Issue(#263) Bug At chatbot
  src/Components/ChatBot/ActionProvider.jsx
  src/Components/ChatBot/MessageParser.jsx
Labels: bug, gssoc, level1

#278 Add feature X
  public/bridge_round.jpg
  src/Pages/Explore.css
  src/Pages/Explore.jsx
Labels: enhancement, gssoc, level1

#141 feat/carousl added to homepage
  package-lock.json
  package.json
  src/Components/Hero/Hero.css
  src/assets/2.jpg
  src/assets/3.jpg
  src/assets/5.jpg
  src/index.css
Labels: enhancement, gssoc, level1

#261 Fixes #259 Linking Explore more to Log in Page
  public/google.png
  src/App.jsx
  src/Components/Hero/Hero.jsx
  src/Components/Login/Login.css
  src/Components/Login/Login.jsx
  src/Components/Signup/Signup.css
Labels: gssoc, level1

#277 Fixed bug #257 navigation links in the footer section and added hovering effects
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/Navbar.jsx
Labels: bug, gssoc, level1

#317 Added new hover effect in testimonials section
  package-lock.json
  src/Components/Testimonials/Testimonial.css
  src/Components/Testimonials/Testimonials.jsx
Labels: gssoc, level1

#299 feat/hover of social media links
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
Labels: enhancement, gssoc, level1

#297 ui of chatbox is enhanced #279
  src/Components/ChatAssistant/ChatAssistant.css
  src/Components/ChatBot/config.jsx
Labels: enhancement, gssoc, level1

#319 AddedPage Links in Footer Section
  src/Components/Footer/Footer.jsx
Labels: bug, gssoc, level1

#309 Enhancing login page styles : issue : #267
  package-lock.json
  src/Components/Footer/Footer.css
  src/Components/Login/Login.css
Labels: bug, gssoc, level1

#333 navdropdown animation added
  package-lock.json
  src/Components/Navbar/Navbar.css
Labels: enhancement, gssoc, level1
