Repository Priyaaa1/StartConnect-Hub, pull requests merged in 2024-07, with the labels that each got.

#579 Added blog page
  package-lock.json
  src/App.jsx
  src/Components/Footer/Footer.jsx
  src/Pages/Blogs.jsx
  src/index.css
Labels: enhancement, gssoc, level3

#590 Creating a Startups Page
  package-lock.json
  package.json
  public/project-1.PNG
  public/project-2.jpg
  public/project-3.jpg
  public/project-4.jpg
  public/project-5.PNG
  public/project-6.PNG
  src/App.jsx
  src/Pages/InvestorManagementPage.jsx
  src/Pages/Startups.jsx
  src/Pages/Startups/EmpowerHer.jsx
  src/Pages/Startups/HeartfeltVentures.jsx
  src/Pages/Startups/HopePhoenix.jsx
  src/Pages/Startups/JustBrew.jsx
  src/Pages/Startups/SheSpark.jsx
  src/Pages/Startups/UnderstandingUnited.jsx
Labels: enhancement, gssoc, level3

#592 Feat: In footer logo,visitors count and star us button added
  src/Components/Footer/Components/Visitors.jsx
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
Labels: enhancement, gssoc, level2

#593 Bug: footer anchor tag fixed
  src/Components/Footer/Footer.css
Labels: enhancement, gssoc, level1

#602 Added the contributors page
  src/App.jsx
  src/Components/Footer/Footer.jsx
  src/Pages/Contributors.css
  src/Pages/Contributors.jsx
Labels: enhancement, gssoc, level2

#608 Hamburger icon needs to replace with close icon after menu opens #542
  package-lock.json
  package.json
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/Navbar.jsx
  src/index.css
Labels: enhancement, gssoc

#599 solved issue dark mode and light mode
  src/App.css
  src/App.jsx
  src/Components/About/About.jsx
  src/Components/Contact/Contact.jsx
Labels: gssoc, level1

#607 Enhanced "Visitors Count's" Working and Added "Styled Button" with "SVG Animation" to Increase UI
  src/Components/Footer/Components/Visitors.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Visitors.jsx
Labels: bug, gssoc, level1

#617 Made "Our Contributors" Page responsive and Align
  src/Pages/Contributors.css
  src/Pages/Contributors.jsx
Labels: bug, gssoc, level1

#615 Add servies to navbar
  src/Components/Navbar/Navbar.jsx
Labels: gssoc, level1

#625 Top to bottom icon hides footer #545
  src/Components/Footer/Footer.css
  src/Components/GoToTop.jsx
Labels: gssoc, level1

#614 Fixed BUG: Navbar Alignment issues while hovering
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/Navbar.jsx
Labels: bug, gssoc, level1

#619 Chatbot "Enhancements" for Better UI/UX #609
  public/bot.gif
  public/botavtar.png
  public/user.png
  src/Components/ChatAssistant/Avatar.jsx
  src/Components/ChatAssistant/ChatAssistant.css
  src/Components/ChatAssistant/ChatAssistant.jsx
  src/Components/ChatAssistant/UserAvatar.jsx
Labels: gssoc, level2

#633 Google Translator
  index.html
Labels: enhancement, gssoc, level1

#643 Expanded the FAQ section
  src/Components/FAQ/data.js
Labels: gssoc, level1

#647 add hover on faq section cards
  src/Components/FAQ/accordian.css
Labels: bug, gssoc

#648 Added "Guided Conversation" Functionality to the Chatbot
  src/Components/ChatAssistant/ChatAssistant.css
  src/Components/ChatBot/ActionProvider.jsx
  src/Components/ChatBot/MessageParser.jsx
  src/Components/ChatBot/Options.jsx
  src/Components/ChatBot/config.jsx
  src/Components/ChatBot/utils.jsx
Labels: enhancement, gssoc, level3
