Repository Priyaaa1/StartConnect-Hub, pull requests merged in 2024-08, with the labels that each got.

#656 enhanced faq section
  src/Components/FAQ/accordian.css
  src/Components/FAQ/accordian.jsx
  src/Components/Footer/Components/faq.jsx
Labels: gssoc, level1

#645 📝[Docs]: Changing of all issue templates and PR template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, gssoc, level1

#667 Add Subscription Form to Footer
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
Labels: gssoc, level1, level2

#666 Fixed footer for all screen sizes
  src/Components/Footer/Footer.css
Labels: gssoc, level1

#657 Googlesign
  src/Components/Login/Login.css
  src/Components/Login/Login.jsx
  src/Components/Signup/Signup.css
  src/Components/Signup/Signup.jsx
Labels: gssoc, level1

#661 Feat stripe payment invest
  .env example
  package.json
  server/.env example
  server/package-lock.json
  server/package.json
  server/server.js
  server/yarn.lock
  src/App.jsx
  src/Pages/Startups/EmpowerHer.jsx
  src/Pages/Startups/HeartfeltVentures.jsx
  src/Pages/Startups/HopePhoenix.jsx
  src/Pages/Startups/JustBrew.jsx
  src/Pages/Startups/SheSpark.jsx
  src/Pages/Startups/UnderstandingUnited.jsx
  src/Pages/pay/CheckoutForm.jsx
  src/Pages/pay/pay.jsx
  src/Pages/pay/pay.scss
  src/main.jsx
  yarn.lock
Labels: gssoc, level3

#699 Repositioned google translate from top to footer
  index.html
  src/Components/Footer/Footer.jsx
  src/Components/GoogleTranslate/GoogleTranslate.jsx
  src/Components/GoogleTranslate/googleTranslate.css
Labels: gssoc, level1

#700 Fixed google login button issue and tweeked signup component UI
  src/Components/Login/Login.css
  src/Components/Signup/Signup.css
Labels: gssoc, level1

#701 Added proper message when no results found for blogs
  src/Pages/Blogs.jsx
  src/assets/no-results.png
Labels: gssoc, level1

#703 Update README.md
  README.md
Labels: documentation, gssoc, level1

#710 Added Icons to Navbar Links
  src/Components/Navbar/Navbar.jsx
Labels: gssoc, level1

#712 validation needs to be done on phone number #676
  src/Components/Contact/Contact.css
  src/Components/Contact/Contact.jsx
Labels: gssoc, level1

#717 ✔️Added Cookie popup to StarConnect!
  src/App.jsx
  src/Components/CookiePolicy/CookieConsent.css
  src/Components/CookiePolicy/CookieConsent.jsx
Labels: gssoc, level2
