Repository Priyaaa1/StartConnect-Hub, pull requests merged in 2024-06, with the labels that each got.

#342 GSSOC: ChatBot updates (Fixes #293)
  src/Components/ChatBot/ActionProvider.jsx
  src/Components/ChatBot/MessageParser.jsx
Labels: bug, gssoc, level1

#351 Resolved "Netlify Routing Navigation Errors" For The Pages
  netlify.toml
  package.json
Labels: bug, gssoc, level1

#354 [BUG]: Login Button
  src/Components/Login/Login.css
  src/Components/Login/Login.jsx
Labels: bug, gssoc, level1

#358 Added Dark Mode Toggle
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/Components/About/About.css
  src/Components/About/About.jsx
  src/Components/Contact/Contact.css
  src/Components/Contact/Contact.jsx
  src/Components/Footer/Footer.css
  src/Components/Navbar/Navbar.jsx
Labels: enhancement, gssoc, level3

#291 #265 image-placement fixed in testimonials
  src/Components/Testimonials/Testimonial.css
  src/Components/Testimonials/Testimonials.jsx
Labels: gssoc, level1

#365 Added preloader
  package-lock.json
  package.json
  src/Components/Preloader/Preloader.css
  src/Components/Preloader/Preloader.jsx
  src/assets/pre.json
  src/main.jsx
Labels: gssoc, level1

#374 Made Contact Page Responsive
  src/Components/Contact/Contact.css
  src/Components/Footer/Components/Main.css
  src/Pages/Explore.css
  src/Pages/Explore.jsx
Labels: gssoc, level1

#383 Solved the issue of page rendering at bottom
  src/Pages/PrivacyPolicy.jsx
  src/Pages/TermsAndConditions.jsx
  src/Pages/VisionAndMission.jsx
Labels: gssoc, level1

#376 Addition of Contributprs logo's and no of forkd pr issue stars count in Readme.md
  README.md
Labels: documentation, gssoc, level1

#356 Updated Footer.jsx
  src/Components/Footer/Footer.jsx
Labels: gssoc, level1

#389 Images replaced
  src/Components/Hero/Hero.css
  src/assets/nile_1.jpg
  src/assets/nile_2.jpg
  src/assets/nile_3.jpg
  src/assets/nile_4.jpg
Labels: gssoc, level1

#379 Updated collaboration link
  src/Components/Footer/Footer.jsx
Labels: gssoc

#381 Resolved Dark Mode Persistance Issue After refreshing
  src/App.jsx
Labels: bug, gssoc, level1

#361 Add the hover effect in the Submit button
  package-lock.json
  package.json
  src/Components/Contact/Contact.css
Labels: enhancement, gssoc

#387 Solved the issue of page rendering at bottom
  src/Pages/FullServiceFund.jsx
Labels: gssoc, level1

#398 Added validation in form
  src/Components/Login/Login.jsx
  src/Components/Signup/Signup.css
  src/Components/Signup/Signup.jsx
Labels: gssoc, level1

#390 The UI is now sorted and completed
  package-lock.json
  src/App.jsx
  src/Components/Hero/Hero.css
  src/Components/Hero/Hero.jsx
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/Navbar.jsx
  src/Components/Testimonials/Testimonial.css
  src/assets/investors.jpeg
  src/assets/investors.png
Labels: bug, gssoc, level2

#410 Added the github icon
  src/Components/Footer/Footer.jsx
Labels: enhancement, gssoc, level1

#413 added auto sliding effect to testimonials
  src/Components/Testimonials/Testimonial.css
  src/Components/Testimonials/Testimonials.jsx
Labels: enhancement, gssoc, level2

#411 Updated toggle switch of light/dark mode
  package-lock.json
  package.json
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/Navbar.jsx
Labels: enhancement, gssoc, level1

#409 Added hovering effect on the footer
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
  src/Components/Navbar/Navbar.jsx
Labels: enhancement, gssoc, level1

#417 Feat: Added a PR template
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: enhancement, gssoc, level1

#425 Resolving Conflict and Refactoring
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Testimonials/Testimonials.jsx
Labels: bug, gssoc, level2

#434 Updated Footer
  package-lock.json
  src/App.jsx
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
Labels: enhancement, gssoc, level1

#442 Auto Commenting when a PR is merged
  .github/workflows/auto-comment-pr-merge.yml
Labels: gssoc, level1

#447 Added issues template for documentation issues
  .github/ISSUE_TEMPLATE/documentation.md
Labels: gssoc, level1

#453 Added hover effect in Header
  package-lock.json
  package.json
  src/App.css
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/Navbar.jsx
  src/index.css
Labels: gssoc, level1

#452 Fixed the outline issue and centered Know more
  src/Pages/Explore.css
  src/Pages/Explore.jsx
Labels: gssoc, level1

#457 Added the feature to auto comment on a new issue creation
  .github/workflows/auto-comment-on-issue.yml
Labels: gssoc, level1

#422 Add start connect hub
  package.json
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/Navbar.jsx
Labels: gssoc, level1

#456 feat: 404 notfound page added with config
  public/404.png
  src/App.jsx
  src/Components/Notfound/Notfound.css
  src/Components/Notfound/Notfound.jsx
Labels: enhancement, gssoc, level2

#468 Replace Twitter with X
  src/Components/Footer/Footer.jsx
Labels: gssoc, level1

#466 Added "Feedback Form/Page" to "Star Connect Hub" Website
  src/App.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Navbar/Navbar.jsx
  src/Pages/FeedbackForm.jsx
  src/Pages/feedback.css
Labels: enhancement, gssoc, level2

#478 [Fixes]: Navbar Responsive, Dark Theme Implemented and Redux State Management Store Implemented 🔥
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/Components/About/About.css
  src/Components/About/About.jsx
  src/Components/Contact/Contact.css
  src/Components/Contact/Contact.jsx
  src/Components/FAQ/accordian.css
  src/Components/Footer/Components/Main.css
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
  src/Components/Login/Login.css
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/Navbar.jsx
  src/Components/Navbar/moon.jpg
  src/Components/Navbar/moon.svg
  src/Components/Navbar/sun.jpg
  src/Components/Navbar/sun.svg
  src/Components/Signup/Signup.css
  src/Components/Testimonials/Testimonial.css
  src/Components/Testimonials/Testimonials.jsx
  src/Components/Title/Title.css
  src/Components/Title/Title.jsx
  src/Pages/Explore.css
  src/Pages/FinancialServices.jsx
  src/Pages/FullServiceFund.jsx
  src/Pages/HowItWorks.jsx
  src/Pages/InvestorManagementPage.jsx
  src/Pages/PrivacyPolicy.jsx
  src/Pages/TermsAndConditions.jsx
  src/Pages/VisionAndMission.jsx
  src/app/store.jsx
  src/features/theme.jsx
  src/index.css
  src/main.jsx
Labels: bug, gssoc, level3

#470 Added Link to "How it Works" Page
  src/Components/Footer/Footer.jsx
  src/Pages/HowItWorks.jsx
Labels: gssoc, level1

#488 Solved footer alignment issue and made it responsive
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
Labels: bug, gssoc, level1

#491 Added "Hover Effect" to "Footer" Content and Links
  package-lock.json
  src/Components/Footer/Footer.css
Labels: enhancement, gssoc, level1

#496 Updated "Feedback Form"
  src/App.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Navbar/Navbar.jsx
  src/Pages/FeedbackForm.jsx
  src/Pages/feedback.css
Labels: gssoc

#426 updated the chatbox
  package-lock.json
  package.json
  src/App.jsx
  src/Components/ChatAssistant/ChatAssistant.css
  src/Components/ChatAssistant/ChatAssistant.jsx
  src/assets/cancel-icon.png
  src/features/theme.jsx
Labels: bug, gssoc, level1

#504 Updated "Contact Email" in Different Pages
  src/Components/Contact/Contact.jsx
  src/Components/FAQ/data.js
  src/Pages/PrivacyPolicy.jsx
  src/Pages/TermsAndConditions.jsx
Labels: gssoc, level1

#511 Resolved the google login functionality Fixes the merge conflict of #503 and issue #340
  src/Components/Login/Login.jsx
Labels: bug, gssoc, level2

#500 Fixed the hamburger issue
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/Navbar.jsx
Labels: bug, gssoc, level2

#513 Fixed login page for mobile screen
  src/Components/Login/Login.css
Labels: bug, gssoc, level1

#523 Designed "Licensing" Page Reflecting "MIT License"
  LICENSE
  src/App.jsx
  src/Components/Footer/Footer.jsx
  src/Pages/Licensing.jsx
Labels: enhancement, gssoc, level2

#526 Added Reset functionality in feedback form
  src/Pages/FeedbackForm.jsx
Labels: bug, gssoc, level1

#535 Made the page responsive
  src/Pages/FeedbackForm.jsx
  src/Pages/feedback.css
Labels: gssoc, level1

#529 Added ForgetPassword Section
  package-lock.json
  package.json
  src/App.jsx
  src/Components/ForgotPassword/ForgotPassword.css
  src/Components/ForgotPassword/ForgotPassword.jsx
  src/Components/Login/Login.jsx
Labels: enhancement, gssoc, level2

#548 Added "Scroll Down Progress bar" to the Website
  src/App.jsx
  src/Components/ProgressBar.jsx
  src/Components/progressbar.css
  src/index.css
Labels: enhancement, gssoc, level1

#551 Fixed the bug
  src/Components/Footer/Footer.jsx
  src/Components/Navbar/Navbar.jsx
Labels: bug, gssoc, level2

#547 Added "Proper Alignments" for "Pages Contents"
  src/Pages/HowItWorks.jsx
  src/Pages/PrivacyPolicy.jsx
  src/Pages/TermsAndConditions.jsx
Labels: gssoc, level1

#553 Implemented "Submitted Confirmation" Pop-Up in Feedback Form
  src/Pages/FeedbackForm.jsx
  src/Pages/feedback.css
Labels: enhancement, gssoc, level2

#563 Improved transition and Fixed texts not being visible when hovered on cards
  src/Components/Hero/Hero.css
  src/Pages/Explore.css
Labels: gssoc
